
version: "3"
services:
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_USER
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER